### PR TITLE
Patterns under the Inform Strategy

### PR DESCRIPTION
**Pull request by p4pnl**
As per work done in the second Radboud/UPM collaboration.
@mohit @npdoty

This large PR adds the patterns we updated and added to create the system of patterns for informing users. Each pattern includes relationships in the Hyde metadata. 

Note that `Active-broadcast-of-presence.md`, `Ambient-notice.md`, `Asynchronous-notice.md`, `Data-breach-notification-pattern.md`, `Layered-policy-design.md`, `Policy-matching-display.md`, `Privacy-aware-network-client.md`, `Privacy-color-coding.md`, `Privacy-dashboard.md`, `Privacy-icons.md` and `Unusual-activities.md` are updated in this PR. Each of these patterns have been extended to have more content, and to be more in line with the other patterns.

### CODE REVIEW

**Comment by npdoty** [comment]
This looks cool! 

I think we might be getting to a point where we will need to try to consolidate some patterns or better explain their differences (I had trouble distinguishing between layered policy notice and the abridged terms and conditions, for example), but I think getting more patterns up, and adding more detail and depth to patterns, is a great direction. Having references and alternative names, as I'm seeing in lots of these, is great.

(I'll try to run a test compilation before approving the merge request, should have time in the next day or so.)

**Comment by HecticSeptic** [comment]
Sounds good

**Review by npdoty — CHANGES_REQUESTED** [review]
Many of these don't quite render correctly in Markdown. Specifically, Markdown requires a blank line before a list of items, and in most or all of these, the Forces and Concerns subsection has a list of items that starts immediately after an HTML comment, and as a result all of those just appear as in a big paragraph.

Once we fix that, I think we can merge this and get this new content on the site!

**Comment by p4pnl** [comment]
@npdoty as per b213820 the affected files now each have an added blank line before the forces. Interestingly, GitHub's markdown flavor was not affected ([e.g](https://github.com/p4pnl/patterns/blob/012aa8ead8993c18ba89474429d763ae34bef9ed/patterns/Impactful-Information-and-Feedback.md)). This discrepancy does feel familiar, though.

**Review by npdoty — APPROVED** [review]

**Comment by npdoty** [comment]
Much better, thanks! There may still be a couple cases where that linebreak issue comes into play (Abridged Terms and Conditions also has bullet points in paragraphs in Examples and Related Patterns) but we can track those in smaller issues and I think we can merge this in the meantime.

**Pull request merged**
