### PR TITLE
P4P privacy (pre)patterns

### PR DESCRIPTION
**Pull request by p4pnl**

### CODE REVIEW

**Comment by npdoty** [comment]
Apologies, can I get some more context here? How do these vary from the privacypatterns.eu patterns? Do we have provenance information for these? (Who developed them, etc.?)

This will be a large amount of content to import all at once, so I'd like us to get it right!

Also, are these all ready to be published publicly? Some of the names/descriptions I don't really understand.

In general, that might be a good indication that for all the patterns in our collection, we should have some metadata about how settled we are on it. e.g. stub, draft, pattern, accepted

**Comment by HecticSeptic** [comment]
The ones which overlapped with privacypatterns.eu were the same patterns, using the schema, only that we had done the reformatting. They're left out of this PR because they've been addressed separately.

Each of the patterns have sources listed, most of them I would say are pre-patterns (draft). Since we did have the draft/pattern distinction in hyde already that seemed fine from here?

**Comment by mohit** [comment]
resolves #4

**Comment by npdoty** [comment]
Yeah, good point: we already have a status metadata field in the existing patterns; but currently I think every pattern is listed as `draft` even though their development varies. I've opened #6 to address that.

Should we also organize the patterns on privacypatterns.org differently based on that status? As this will be a very large import, we might need pagination or categorization for this many patterns to still be reasonably browsable.

**Comment by p4pnl** [comment]
I think that the p4p patterns can then be given the `stub` status except for the ones we flesh out further than what we find in literature, as they're probably more pre-pattern than the ones already live. 

I think organising differently on the website is a good idea, but with the strategies/tactics categorisation it may not be necessary to do so by status.

Since I made this pull request before the pripare/Ulm patterns were added, can I make the `stub` changes and then push or will there be issues?

**Pull request closed without merging**
